# Root

[[redirects]]
  from = "https://thestake2.netlify.app/"
  to = "https://thestake2.netlify.app/websites/"
  status = 301
  force = true

# "My Little Pony: Friendship Is Magic"

[[redirects]]
  from = "https://thestake2.netlify.app/mlpfim/"
  to = "https://thestake2.netlify.app/My Little Pony/Friendship Is Magic/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/My%20Little%20Pony%20Friendship%20Is%20Magic/"
  to = "https://thestake2.netlify.app/My%20Little%20Pony/Friendship%20Is%20Magic/"
  status = 301
  force = true

# Watch History

[[redirects]]
  from = "https://thestake2.netlify.app/assistidos/"
  to = "https://thestake2.netlify.app/Watch History/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/watch/"
  to = "https://thestake2.netlify.app/Watch History/"
  status = 301
  force = true

# Play History

[[redirects]]
  from = "https://thestake2.netlify.app/jogos/"
  to = "https://thestake2.netlify.app/Play History/"
  status = 301
  force = true

# Tasks

[[redirects]]
  from = "https://thestake2.netlify.app/tarefas/"
  to = "https://thestake2.netlify.app/Tasks/"
  status = 301
  force = true

# Music

[[redirects]]
  from = "https://thestake2.netlify.app/musica/"
  to = "https://thestake2.netlify.app/music/"
  status = 301
  force = true

# years

[[redirects]]
  from = "https://thestake2.netlify.app/anos/"
  to = "https://thestake2.netlify.app/years/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/years/2018/"
  to = "https://thestake2.netlify.app/2018/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/years/2019/"
  to = "https://thestake2.netlify.app/2019/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/years/2020/"
  to = "https://thestake2.netlify.app/2020/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/years/2021/"
  to = "https://thestake2.netlify.app/2021/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/years/2022/"
  to = "https://thestake2.netlify.app/2022/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/years/2023/"
  to = "https://thestake2.netlify.app/2023/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/years/2024/"
  to = "https://thestake2.netlify.app/2024/"
  status = 301
  force = true

# Stories

[[redirects]]
  from = "https://thestake2.netlify.app/historias/"
  to = "https://thestake2.netlify.app/Stories/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/historia/"
  to = "https://thestake2.netlify.app/Stories/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/story/"
  to = "https://thestake2.netlify.app/Stories/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/hist%C3%B3rias/"
  to = "https://thestake2.netlify.app/Stories/"
  status = 301
  force = true

# The Life of Littletato

[[redirects]]
  from = "https://thestake2.netlify.app/pequenata/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/littletato/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/story/littletato/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/stories/littletato/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/historia/pequenata/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/historias/pequenata/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/a%20vida%20de%20pequenata/"
  to = "https://thestake2.netlify.app/The%20Life%20of%20Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/The_Life_of_Littletato/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/the_life_of_littletato/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

# SpaceLiving

[[redirects]]
  from = "https://thestake2.netlify.app/story/spaceliving/"
  to = "https://thestake2.netlify.app/SpaceLiving/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/stories/spaceliving/"
  to = "https://thestake2.netlify.app/SpaceLiving/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/historia/spaceliving/"
  to = "https://thestake2.netlify.app/SpaceLiving/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/historias/spaceliving/"
  to = "https://thestake2.netlify.app/SpaceLiving/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/new%20world/spaceliving/"
  to = "https://thestake2.netlify.app/SpaceLiving/"
  status = 301
  force = true

# The Story of the Bulkan Siblings

[[redirects]]
  from = "https://thestake2.netlify.app/bulkan/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/story/bulkan/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/stories/bulkan/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/historia/bulkan/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/historias/bulkan/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/a%20história%20dos%20irmãos%20bulkan/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/the_story_of_the_bulkan_siblings/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

# The Secret of the Crystals

[[redirects]]
  from = "https://thestake2.netlify.app/o%20segredo%20dos%20cristais/"
  to = "https://thestake2.netlify.app/The Secret of the Crystals/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/the_secret_of_the_crystals/"
  to = "https://thestake2.netlify.app/The Secret of the Crystals/"
  status = 301
  force = true

# Desert Island

[[redirects]]
  from = "https://thestake2.netlify.app/ilha%20deserta/"
  to = "https://thestake2.netlify.app/Desert Island/"
  status = 301
  force = true

# Stake2

[[redirects]]
  from = "https://thestake2.netlify.app/eu/"
  to = "https://thestake2.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/me/"
  to = "https://thestake2.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/izaque/"
  to = "https://thestake2.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/isaac/"
  to = "https://thestake2.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/sobre%20mim/"
  to = "https://thestake2.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/about%20me/"
  to = "https://thestake2.netlify.app/stake2/"
  status = 301
  force = true

# Plugins

[[plugins]]
  package = "@netlify/plugin-sitemap"