# Root

[[redirects]]
  from = "https://thestake2.netlify.app/"
  to = "https://thestake2.netlify.app/websites/"
  status = 301
  force = true

# "My Little Pony: Friendship Is Magic"

[[redirects]]
  from = "https://thestake2.netlify.app/mlpfim/"
  to = "https://thestake2.netlify.app/My Little Pony/Friendship Is Magic/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/My Little Pony Friendship Is Magic/"
  to = "https://thestake2.netlify.app/My Little Pony/Friendship Is Magic/"
  status = 301
  force = true

# Watch HiStory

[[redirects]]
  from = "https://thestake2.netlify.app/Assistidos/"
  to = "https://thestake2.netlify.app/Watch HiStory/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/Watch/"
  to = "https://thestake2.netlify.app/Watch HiStory/"
  status = 301
  force = true

# Play HiStory

[[redirects]]
  from = "https://thestake2.netlify.app/Jogos/"
  to = "https://thestake2.netlify.app/Play HiStory/"
  status = 301
  force = true

# Tasks

[[redirects]]
  from = "https://thestake2.netlify.app/Tarefas/"
  to = "https://thestake2.netlify.app/Tasks/"
  status = 301
  force = true

# Music

[[redirects]]
  from = "https://thestake2.netlify.app/Musica/"
  to = "https://thestake2.netlify.app/music/"
  status = 301
  force = true

# Years

[[redirects]]
  from = "https://thestake2.netlify.app/Anos/"
  to = "https://thestake2.netlify.app/Years/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/Years/2018/"
  to = "https://thestake2.netlify.app/2018/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/Years/2019/"
  to = "https://thestake2.netlify.app/2019/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/Years/2020/"
  to = "https://thestake2.netlify.app/2020/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/Years/2021/"
  to = "https://thestake2.netlify.app/2021/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/Years/2022/"
  to = "https://thestake2.netlify.app/2022/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/Years/2023/"
  to = "https://thestake2.netlify.app/2023/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/Years/2024/"
  to = "https://thestake2.netlify.app/2024/"
  status = 301
  force = true

# Stories

[[redirects]]
  from = "https://thestake2.netlify.app/Historias/"
  to = "https://thestake2.netlify.app/Stories/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/historia/"
  to = "https://thestake2.netlify.app/Stories/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/Story/"
  to = "https://thestake2.netlify.app/Stories/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/hist%C3%B3rias/"
  to = "https://thestake2.netlify.app/Stories/"
  status = 301
  force = true

# The Life of Littletato

[[redirects]]
  from = "https://thestake2.netlify.app/Pequenata/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/Littletato/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/Story/Littletato/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/Stories/Littletato/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/historia/Pequenata/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/Historias/Pequenata/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/A Vida de Pequenata/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/The_Life_of_Littletato/"
  to = "https://thestake2.netlify.app/The Life of Littletato/"
  status = 301
  force = true

# SpaceLiving

[[redirects]]
  from = "https://thestake2.netlify.app/Story/SpaceLiving/"
  to = "https://thestake2.netlify.app/SpaceLiving/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/Stories/SpaceLiving/"
  to = "https://thestake2.netlify.app/SpaceLiving/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/Historia/SpaceLiving/"
  to = "https://thestake2.netlify.app/SpaceLiving/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/Historias/SpaceLiving/"
  to = "https://thestake2.netlify.app/SpaceLiving/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/New World/SpaceLiving/"
  to = "https://thestake2.netlify.app/SpaceLiving/"
  status = 301
  force = true

# The Story of the Bulkan Siblings

[[redirects]]
  from = "https://thestake2.netlify.app/Bulkan/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/Story/Bulkan/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/Stories/Bulkan/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/historia/Bulkan/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/Historias/Bulkan/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/A Hist%C3%B3ria dos Irmãos Bulkan/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/A História dos Irmãos Bulkan/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/The_Story_of_the_Bulkan_Siblings/"
  to = "https://thestake2.netlify.app/The Story of the Bulkan Siblings/"
  status = 301
  force = true

# The Secret of the Crystals

[[redirects]]
  from = "https://thestake2.netlify.app/O Segredo dos Cristais/"
  to = "https://thestake2.netlify.app/The Secret of the Crystals/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/The_Secret_of_the_Crystals/"
  to = "https://thestake2.netlify.app/The Secret of the Crystals/"
  status = 301
  force = true

# Desert Island

[[redirects]]
  from = "https://thestake2.netlify.app/Ilha Deserta/"
  to = "https://thestake2.netlify.app/Desert Island/"
  status = 301
  force = true

# Stake2

[[redirects]]
  from = "https://thestake2.netlify.app/eu/"
  to = "https://thestake2.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/me/"
  to = "https://thestake2.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/izaque/"
  to = "https://thestake2.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/isaac/"
  to = "https://thestake2.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/sobre mim/"
  to = "https://thestake2.netlify.app/stake2/"
  status = 301
  force = true

[[redirects]]
  from = "https://thestake2.netlify.app/about me/"
  to = "https://thestake2.netlify.app/stake2/"
  status = 301
  force = true

# Plugins

[[plugins]]
  package = "@netlify/plugin-sitemap"